version: '2'
services:
  postgres:
    image: postgres
    network_mode: host
  redis:
    image: redis:alpine
    network_mode: host
    ports:
      - "6379:6379"
  survey-training-preprocessor-test:
    image: python:3.5
    network_mode: host
    volumes:
      # - ../assets:/usr/src/app/assets
      - ./:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && pip install -r requirements.txt && python -u test.py\""
    depends_on:
      - postgres
      - redis
